### ISSUE TITLE
[Vacancy Bay Area] Need a "percent of total homes in tract" visualization option

### ISSUE THREAD

**Issue by jlhawn** [DarrellOwensRCD/infoTransit#1]
Looking at the visualization for the "Sold, Not Yet Occupied" in both quantity and percent, I noticed that the percentage visualization is not what I thought it was. I was expecting it to be the percentage of homes in the tract which are in that vacancy category but instead it is percentage of **vacancies** in the tract which I think is not as useful. Looking at the source code, I don't see an easy way to set that option.

**Comment by DarrellOwensRCD** [comment]
Thats the other option

**Comment by jlhawn** [comment]
Yes, you're right! It does appear to be in the data already. I've annotated this screenshot to show how the vacancy rate for "sold, not yet occupied" is a very low 1.4% in the Northeast SOMA tract.

![Screen Shot 2022-02-08 at 8 35 33 PM](https://user-images.githubusercontent.com/1441929/153294634-6cb6260b-6794-41da-a7d7-2928b73c444a.png)
.

**Comment by DarrellOwensRCD** [comment]
I've changed the color coding in the % tract to reflect the percentage of total housing and not vacant housing which I admit is a more useful visual.
